#!/usr/bin/env python3
"""Generate cross-reference indices for the c500-kernel-wiki.

Mirrors upstream KernelWiki's generate-indices.py in shape — frontmatter-driven,
emitting markdown tables into queries/ — but with the indices that matter for a
measurement-first knowledge base. `by-probe.md` is the one upstream does not
have: it is the reverse index from each probe to the pages that cite it, so that
re-running or changing a probe immediately shows which pages need re-verification.

Usage:
    python3 scripts/generate-indices.py
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate import (
    PROBES_DIR,
    QUERIES_DIR,
    SKILL_ROOT,
    WIKI_DIR,
    extract_frontmatter,
    read_body,
)

_AUTO_NOTE = "> Auto-generated by scripts/generate-indices.py. Do not edit manually."

_PROBE_REF_RE = re.compile(r"probes/([A-Za-z0-9_.]+\.cu)")


def load_pages():
    pages = []
    for md in sorted(WIKI_DIR.rglob("*.md")):
        fm, err = extract_frontmatter(md)
        if err or not isinstance(fm, dict):
            continue
        pages.append(
            {
                "path": md.relative_to(SKILL_ROOT).as_posix(),
                "fm": fm,
                "body": read_body(md),
            }
        )
    return pages


def qlink(page_path):
    """Link relative from queries/ to a wiki page path."""
    return f"../{page_path}"


def probes_root(name):
    """Render a probe citation; in-page scripts are not files under probes/."""
    return f"probes/{name}" if name.endswith(".cu") else name


def write_index(name, title, intro, lines):
    path = QUERIES_DIR / name
    out = ["# " + title, "", _AUTO_NOTE, ""]
    if intro:
        out += [intro, ""]
    out += lines
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {path.relative_to(SKILL_ROOT)}")


def generate_by_type(pages):
    lines = ["| Page | Type | Provenance | Confidence | Probe |", "|---|---|---|---|---|"]
    for p in pages:
        fm = p["fm"]
        title = str(fm.get("title", "Untitled")).replace("|", "\\|")
        lines.append(
            f"| [{title}]({qlink(p['path'])}) | {fm.get('type')} | {fm.get('provenance')} "
            f"| {fm.get('confidence')} | {fm.get('probe', '—') or '—'} |"
        )
    write_index(
        "by-type.md",
        "Index: By Page Type",
        "Every knowledge page, grouped by what kind of fact it is. "
        "`provenance` says how the page's claims were established; `probe` is the "
        "reproducer for `provenance: measured` pages.",
        lines,
    )


def generate_by_symptom(pages):
    """Symptom → page. Symptoms are mined from each page's tags, which carry the
    observable-cause vocabulary (memory-bound, launch-overhead, register-spill…)."""
    symptom_map = {}
    for p in pages:
        tags = p["fm"].get("tags")
        tags = tags if isinstance(tags, list) else ([tags] if tags else [])
        for t in tags:
            symptom_map.setdefault(str(t), []).append(p)

    lines = ["| Tag | Pages |", "|---|---|"]
    for tag in sorted(symptom_map):
        refs = ", ".join(
            f"[{p['fm'].get('title', '?')}]({qlink(p['path'])})" for p in symptom_map[tag]
        )
        lines.append(f"| `{tag}` | {refs} |")

    write_index(
        "by-symptom.md",
        "Index: By Tag",
        "Entry point when you know the symptom or topic but not the page. Tags are "
        "drawn from page frontmatter; this is the closest thing this wiki has to the "
        "upstream by-problem index, which is built from a `symptoms:` field we do "
        "not carry — mine tags instead.",
        lines,
    )


def generate_by_probe(pages):
    """The reverse index: probe → pages citing it. Changing a probe's numbers
    invalidates every page listed beside it."""
    probe_to_pages = {}
    for p in pages:
        cited = set(_PROBE_REF_RE.findall(p["body"]))
        fm_probe = p["fm"].get("probe")
        if isinstance(fm_probe, str):
            cited.add(fm_probe.split("/")[-1])
        for name in sorted(cited):
            probe_to_pages.setdefault(name, []).append(p)

    lines = ["| Probe | Cited by | Compiles under |", "|---|---|---|"]
    for probe in sorted(probe_to_pages):
        # Non-.cu probes are in-page scripts (torch.benchmark snippets), not
        # files under probes/ — they are verified by running the page's own
        # snippet, not by this index.
        is_file_probe = probe.endswith(".cu")
        exists = (PROBES_DIR / probe).is_file() if is_file_probe else True
        refs = ", ".join(
            f"[{p['fm'].get('title', '?')}]({qlink(p['path'])})" for p in probe_to_pages[probe]
        )
        status = "yes" if exists else "**MISSING**"
        lines.append(f"| `{probes_root(probe)}` | {refs} | {status} |")

    # Surface probes that exist but back no page: dead weight, or a page that
    # forgot to cite its evidence.
    cited_set = set(probe_to_pages)
    orphan = sorted(p.name for p in PROBES_DIR.glob("*.cu") if p.name not in cited_set)
    if orphan:
        lines += ["", "## Probes cited by no page", ""]
        lines += ["These compile but no page references them. Either the page that "
                  "depends on them is missing, or the probe is obsolete.", ""]
        for name in orphan:
            lines.append(f"- `probes/{name}`")

    write_index(
        "by-probe.md",
        "Index: By Probe (reverse)",
        "The evidence reverse index. Each row is a microbenchmark and every page "
        "that cites its numbers. When a probe is re-run after an SDK upgrade, "
        "these are the pages that must be re-verified. This index has no upstream "
        "equivalent — upstream's evidence is PRs, which do not change, but these "
        "probes do.",
        lines,
    )


def main():
    if not WIKI_DIR.is_dir():
        print("wiki/ not found", file=sys.stderr)
        sys.exit(1)
    QUERIES_DIR.mkdir(parents=True, exist_ok=True)

    pages = load_pages()
    if not pages:
        print("no pages with parseable frontmatter found", file=sys.stderr)
        sys.exit(1)

    generate_by_type(pages)
    generate_by_symptom(pages)
    generate_by_probe(pages)
    print(f"\nIndexed {len(pages)} pages.")


if __name__ == "__main__":
    main()
